source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'mysql2'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'backgroundrb-rails3', :require => 'backgroundrb'
gem 'will_paginate', '~> 3.0.pre2'
gem 'paperclip'
gem "chronic", '0.2.3'
gem "hpricot", '0.8.2'
gem "httparty", '0.5.2'
gem "packet", '0.1.15'
gem "twitter", '0.9.7'
gem 'calendar_date_select', :git => 'http://github.com/paneq/calendar_date_select.git', :branch => 'rails3test'
gem "annotate", '2.4.0'
